In [1]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 4.4 MB 5.2 MB/s 
     |████████████████████████████████| 596 kB 36.1 MB/s 
     |████████████████████████████████| 101 kB 3.9 MB/s 
     |████████████████████████████████| 6.6 MB 54.1 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [2]:
!pip install sentencepiece

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.2 MB 5.0 MB/s 


In [3]:
!pip3 install mvlearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 2.1 MB 5.1 MB/s 
     |████████████████████████████████| 38.1 MB 341 kB/s 
  Attempting uninstall: scipy
    Found existing installation: scipy 1.4.1
    Uninstalling scipy-1.4.1:
      Successfully uninstalled scipy-1.4.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.


In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
import os
os.chdir('drive/MyDrive/William_2022/DATASETS/main_trans_ZuCo')

In [66]:
!python3 DCCA.py

[ Epoch 0 ]
- (Training)  :   0% 0/5 [00:00<?, ?it/s]/content/drive/.shortcut-targets-by-id/1pzxxbb04a-cju1xepvLaBroeYAKl_mTd/William_2022/DATASETS/main_trans_ZuCo/CCA.py:53: UserWarning: torch.symeig is deprecated in favor of torch.linalg.eigh and will be removed in a future PyTorch release.
The default behavior has changed from using the upper triangular portion of the matrix by default to using the lower triangular portion.
L, _ = torch.symeig(A, upper=upper)
should be replaced with
L = torch.linalg.eigvalsh(A, UPLO='U' if upper else 'L')
and
L, V = torch.symeig(A, eigenvectors=True)
should be replaced with
L, V = torch.linalg.eigh(A, UPLO='U' if upper else 'L') (Triggered internally at  ../aten/src/ATen/native/BatchLinearAlgebra.cpp:2524.)
  [D1, V1] = torch.symeig(SigmaHat11, eigenvectors=True)
    - [Info] The checkpoint file has been updated.
  - (Training)  loss: -0.01692 elapse: 0.003 min
  - (Validation)  loss: -0.00386, elapse: 0.003 min
[ Epoch 1 ]
    - [Info] The checkpoi

In [69]:
!python3 DCCA_text.py

[ Epoch 0 ]
DCCA_text.py:56: RuntimeWarning: invalid value encountered in long_scalars
  pre_i = [cm[i, i] / total_pred[i] for i in range(class_num)]
[nan, 0.4, nan]
[0.0, 1.0, 0.0]
acc_SP is : 0.4
pre_i is : [0.0, 0.4, 0.0]
rec_i is : [0.0, 1.0, 0.0]
F1_i is : [0.0, 0.5714285714285715, 0.0]
    - [Info] The checkpoint file has been updated.
  - (Training)  loss:  1.30686, accuracy: 31.699 %, elapse: 0.003 min
train_cm: [[  2 116   0]
 [  2  95   0]
 [  2  89   0]]
  - (Validation)  loss:  1.28075, accuracy: 40.000 %, elapse: 0.003 min
valid_cm: [[ 0 20  0]
 [ 0 24  0]
 [ 0 16  0]]
[ Epoch 1 ]
DCCA_text.py:56: RuntimeWarning: invalid value encountered in long_scalars
  pre_i = [cm[i, i] / total_pred[i] for i in range(class_num)]
[nan, 0.4, nan]
[0.0, 1.0, 0.0]
acc_SP is : 0.4
pre_i is : [0.0, 0.4, 0.0]
rec_i is : [0.0, 1.0, 0.0]
F1_i is : [0.0, 0.5714285714285715, 0.0]
    - [Info] The checkpoint file has been updated.
  - (Training)  loss:  1.30853, accuracy: 38.889 %, elapse: 0.003 m

In [70]:
!python3 DCCA_eeg.py

[ Epoch 0 ]
DCCA_eeg.py:56: RuntimeWarning: invalid value encountered in long_scalars
  pre_i = [cm[i, i] / total_pred[i] for i in range(class_num)]
[nan, 0.4, nan]
[0.0, 1.0, 0.0]
acc_SP is : 0.4
pre_i is : [0.0, 0.4, 0.0]
rec_i is : [0.0, 1.0, 0.0]
F1_i is : [0.0, 0.5714285714285715, 0.0]
    - [Info] The checkpoint file has been updated.
  - (Training)  loss:  8.03360, accuracy: 29.085 %, elapse: 0.003 min
train_cm: [[  0 116   0]
 [  0  89   0]
 [  0 101   0]]
  - (Validation)  loss:  7.13672, accuracy: 40.000 %, elapse: 0.003 min
valid_cm: [[ 0 20  0]
 [ 0 24  0]
 [ 0 16  0]]
[ Epoch 1 ]
DCCA_eeg.py:56: RuntimeWarning: invalid value encountered in long_scalars
  pre_i = [cm[i, i] / total_pred[i] for i in range(class_num)]
[nan, 0.4, nan]
[0.0, 1.0, 0.0]
acc_SP is : 0.4
pre_i is : [0.0, 0.4, 0.0]
rec_i is : [0.0, 1.0, 0.0]
F1_i is : [0.0, 0.5714285714285715, 0.0]
    - [Info] The checkpoint file has been updated.
  - (Training)  loss:  7.92738, accuracy: 29.739 %, elapse: 0.003 min

In [ ]:
import pandas as pd
import numpy as np
import torch

In [ ]:
ZAB = pd.read_csv('preprocessed_eeg/ZAB_mean.csv')

In [ ]:
X = ZAB.iloc[: ,3:]
y = ZAB[['sentiment']]

In [ ]:
X.round(3)

0      1      2      3      4      5      6      7      8      9  \
0    0.115  0.144  0.334  0.435  0.521  0.468  0.306  0.346  0.467  0.562   
1    0.150  0.166  0.387  0.342  0.411  0.474  0.353  0.333  0.488  0.474   
2    0.128  0.146  0.365  0.419  0.474  0.403  0.292  0.278  0.432  0.506   
3    0.121  0.124  0.279  0.401  0.351  0.402  0.304  0.384  0.624  0.447   
4    0.115  0.126  0.314  0.474  0.532  0.474  0.282  0.379  0.663  0.716   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
395  1.166  1.081  1.085  0.926  0.840  0.386  0.631  0.813  0.897  1.063   
396  1.369  1.312  1.164  0.913  0.733  0.351  0.827  0.958  0.941  0.975   
397  1.454  1.283  1.102  0.693  0.588  0.348  0.624  0.647  0.708  0.830   
398  0.998  1.052  1.016  0.908  0.770  0.446  0.840  0.891  0.926  1.102   
399  1.146  1.076  0.991  0.679  0.495  0.323  0.595  0.640  0.602  0.859   

     ...   95.7   96.7   97.7   98.7   99.7  100.7  101.7  102.7  103.7  104.7  
0    ...  0.229  0.178  0.145  0.320  0.174  0.690  0.189  0.169  0.237      0  
1    ...  0.223  0.191  0.170  0.293  0.162  0.820  0.204  0.198  0.246      0  
2    ...  0.260  0.213  0.111  0.397  0.148  0.609  0.174  0.134  0.289      0  
3    ...  0.254  0.218  0.154  0.353  0.168  0.705  0.187  0.182  0.342      0  
4    ...  0.340  0.292  0.131  0.400  0.125  0.812  0.210  0.139  0.357      0  
..   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
395  ...  0.914  1.221  1.231  1.098  0.541  0.275  0.962  1.321  1.186      0  
396  ...  1.003  1.233  1.173  1.180  0.566  0.220  1.105  1.391  1.293      0  
397  ...  1.142  1.443  1.214  1.054  0.717  0.346  1.177  1.335  1.212      0  
398  ...  1.153  1.350  1.307  1.395  0.663  0.255  1.249  1.632  1.448      0  
399  ...  0.667  0.809  0.775  0.806  0.508  0.279  0.776  1.014  0.916      0  

[400 rows x 839 columns]

In [ ]:
df.replace([np.inf, -np.inf], 0, inplace=True)


In [ ]:
df

sentiment         0         1         2         3         4         5  \
0            1  0.115292  0.143879  0.334241  0.434646  0.520795  0.468173   
1            2  0.149551  0.166466  0.387147  0.342261  0.410666  0.474177   
2            0  0.128100  0.146247  0.364835  0.419477  0.474424  0.402994   
3            2  0.120657  0.124477  0.278609  0.401074  0.350653  0.401724   
4            1  0.114699  0.126094  0.314186  0.473659  0.532056  0.473613   
..         ...       ...       ...       ...       ...       ...       ...   
395          2  1.165944  1.080790  1.085385  0.925674  0.839938  0.385502   
396          0  1.369036  1.311738  1.164263  0.912532  0.733433  0.351036   
397          2  1.453818  1.283306  1.102204  0.693336  0.587966  0.347930   
398          0  0.997968  1.052413  1.015506  0.907788  0.770344  0.445978   
399          2  1.146155  1.075657  0.990697  0.679350  0.494542  0.322692   

            6         7         8  ...      95.7      96.7      97.7  \
0    0.306373  0.346440  0.466853  ...  0.229387  0.178027  0.144655   
1    0.353018  0.332580  0.488462  ...  0.223091  0.191049  0.170279   
2    0.292123  0.278302  0.432163  ...  0.260286  0.213303  0.110620   
3    0.303856  0.384240  0.623583  ...  0.253996  0.217986  0.154110   
4    0.282160  0.379398  0.662826  ...  0.340485  0.292042  0.131178   
..        ...       ...       ...  ...       ...       ...       ...   
395  0.631342  0.812552  0.897377  ...  0.913871  1.221471  1.231353   
396  0.827040  0.957696  0.941271  ...  1.002765  1.233011  1.173364   
397  0.623828  0.647208  0.707732  ...  1.141842  1.442878  1.214217   
398  0.839517  0.890748  0.925847  ...  1.153078  1.350271  1.307005   
399  0.595114  0.639751  0.601761  ...  0.667356  0.809203  0.774543   

         98.7      99.7     100.7     101.7     102.7     103.7  104.7  
0    0.320253  0.174269  0.690055  0.188504  0.169423  0.237246      0  
1    0.293045  0.161509  0.820038  0.204374  0.197841  0.246464      0  
2    0.396562  0.147582  0.609134  0.173841  0.133698  0.289041      0  
3    0.352517  0.167664  0.704545  0.187002  0.182403  0.341818      0  
4    0.400218  0.125483  0.811744  0.209772  0.138863  0.357171      0  
..        ...       ...       ...       ...       ...       ...    ...  
395  1.098190  0.540824  0.275063  0.962136  1.320621  1.186124      0  
396  1.179934  0.565974  0.219899  1.105031  1.391419  1.293336      0  
397  1.054010  0.717485  0.346375  1.177364  1.335392  1.211883      0  
398  1.394599  0.663207  0.255053  1.248587  1.632364  1.447959      0  
399  0.806132  0.507828  0.278627  0.776467  1.014267  0.916012      0  

[400 rows x 840 columns]

In [ ]:
df = df.loc[(df != 0).any(axis=1)]


In [ ]:
df = df.reset_index()

In [ ]:
df

index  sentiment         0         1         2         3         4  \
0        0          1  0.115292  0.143879  0.334241  0.434646  0.520795   
1        1          2  0.149551  0.166466  0.387147  0.342261  0.410666   
2        2          0  0.128100  0.146247  0.364835  0.419477  0.474424   
3        3          2  0.120657  0.124477  0.278609  0.401074  0.350653   
4        4          1  0.114699  0.126094  0.314186  0.473659  0.532056   
..     ...        ...       ...       ...       ...       ...       ...   
392    395          2  1.165944  1.080790  1.085385  0.925674  0.839938   
393    396          0  1.369036  1.311738  1.164263  0.912532  0.733433   
394    397          2  1.453818  1.283306  1.102204  0.693336  0.587966   
395    398          0  0.997968  1.052413  1.015506  0.907788  0.770344   
396    399          2  1.146155  1.075657  0.990697  0.679350  0.494542   

            5         6         7  ...      95.7      96.7      97.7  \
0    0.468173  0.306373  0.346440  ...  0.229387  0.178027  0.144655   
1    0.474177  0.353018  0.332580  ...  0.223091  0.191049  0.170279   
2    0.402994  0.292123  0.278302  ...  0.260286  0.213303  0.110620   
3    0.401724  0.303856  0.384240  ...  0.253996  0.217986  0.154110   
4    0.473613  0.282160  0.379398  ...  0.340485  0.292042  0.131178   
..        ...       ...       ...  ...       ...       ...       ...   
392  0.385502  0.631342  0.812552  ...  0.913871  1.221471  1.231353   
393  0.351036  0.827040  0.957696  ...  1.002765  1.233011  1.173364   
394  0.347930  0.623828  0.647208  ...  1.141842  1.442878  1.214217   
395  0.445978  0.839517  0.890748  ...  1.153078  1.350271  1.307005   
396  0.322692  0.595114  0.639751  ...  0.667356  0.809203  0.774543   

         98.7      99.7     100.7     101.7     102.7     103.7  104.7  
0    0.320253  0.174269  0.690055  0.188504  0.169423  0.237246      0  
1    0.293045  0.161509  0.820038  0.204374  0.197841  0.246464      0  
2    0.396562  0.147582  0.609134  0.173841  0.133698  0.289041      0  
3    0.352517  0.167664  0.704545  0.187002  0.182403  0.341818      0  
4    0.400218  0.125483  0.811744  0.209772  0.138863  0.357171      0  
..        ...       ...       ...       ...       ...       ...    ...  
392  1.098190  0.540824  0.275063  0.962136  1.320621  1.186124      0  
393  1.179934  0.565974  0.219899  1.105031  1.391419  1.293336      0  
394  1.054010  0.717485  0.346375  1.177364  1.335392  1.211883      0  
395  1.394599  0.663207  0.255053  1.248587  1.632364  1.447959      0  
396  0.806132  0.507828  0.278627  0.776467  1.014267  0.916012      0  

[397 rows x 841 columns]

In [ ]:
print("printing column name where infinity is present")
col_name = df.columns.to_series()[np.isinf(df).any()]
print(col_name)
  
# printing row index with infinity
print()
print("printing row index with infinity ")
  
r = df.index[np.isinf(df).any(1)]
print(r)

printing column name where infinity is present
Series([], dtype: object)

printing row index with infinity 
Int64Index([], dtype='int64')


In [ ]:
df_train_eeg = ZAB.iloc[:, 3:]

In [ ]:
df = pd.concat([y, df_train_eeg], axis=1)

In [ ]:
ZAB.values

array([[0, '1',
        'Presents a good case while failing to provide a reason for us to care beyond the very basic dictums of human decency.',
        ..., 0.237246335, 0, 22],
       [1, '2',
        'Beautifully crafted, engaging filmmaking that should attract upscale audiences hungry for quality and a nostalgic, twisty yarn that will keep them guessing.',
        ..., 0.246464431, 0, 22],
       [2, '0',
        'Bread, My Sweet has so many flaws it would be easy for critics to shred it.',
        ..., 0.289040804, 0, 16],
       ...,
       [397, '2',
        "It's not a particularly good film, but neither is it a monsterous one.",
        ..., 1.211882591, 0, 13],
       [398, '0',
        "Men in Black II achieves ultimate insignificance -- it's the sci-fi comedy spectacle as Whiffle-Ball epic.",
        ..., 1.447958827, 0, 16],
       [399, '2', 'Martyr gets royally screwed and comes back for more.',
        ..., 0.916012228, 0, 9]], dtype=object)

In [ ]:
ZAB['token_count'] = ZAB.new_words.str.replace(',','').str.split().str.len()
token = ZAB.filter(['new_words','token_count'])

In [ ]:
token['token_count'].mean()

17.8225